networks:
    laravel:

volumes:
    db-data:
        driver: local

services:

  web:
    image: nginx:stable-alpine
    container_name: 'nginx_app'
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    platform: linux/amd64
    image: mysql:8.0.25
    container_name: 'mysql_app'
    restart: unless-stopped
    ports:
      - "3316:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 'php_app'
    volumes:
      - .:/var/www/html
    ports:
      - "9003:9000"
    networks:
      - laravel
